lift subsystem
Programming-Trigon/2019RobotCode pull request #2
Opened 2019-01-23 18:18 UTC by Mboesn

2019-01-23 20:14 UTC, HilelAmiel requested changes
great code, pay attention to my commants i think you need to start rechange things from robot class.

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
>    private static final String kCustomAuto = "My Auto";
first of all we want the code to be clean from comments, please remove all comments that created automaticly when creating the robot project.

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
>    @Override
also here

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
> +
names: LIFT_ENCODER_CHANNEL_A, LIFT_ENCODER_CHANNEL_B

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
>    @Override
commants...

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Robot.java
>     */
and commants...

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/RobotMap.java
> +
delete commants

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/RobotMap.java
> +
i want you to make it more clear which value (like LIFT_LEFT_MOTOR) is port of PWM (motor controllers) and which values are ports of DIO (sensors).

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +
delete commants

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +public class Lift extends Subsystem {
also here

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +
names: liftRightMotor, liftLeftMotor, liftEncoder
and make the SpeedControllerGroup ( = new SpeedControllerGroup(this.liftMotorLeft, this.liftMotorRight); ) in the class constractor after the client write which liftRightMotor and liftLeftMotor he use in the main class -> Robot.java

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +  }
we want to know what is the hight **(in meters)** the lift system got not in ticks, so make a math calculation (if you use parameters we dont know put then in robot map (yeah fine put them there) and make TODO there that tell us we need to masure them or find what are they when we will have robot...
also change the function name to getHight()

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +    liftMotorGroup.set(power);
name: double speed (not power)

2019-01-23 20:14 UTC, HilelAmiel commented on src/main/java/frc/robot/Subsystems/Lift.java
> +  }
delete commants

2019-01-27 18:40 UTC, esh4 commented on src/main/java/frc/robot/Robot.java
> +
Not using encoders...

2019-01-27 18:53 UTC, esh4 requested changes

2019-01-27 18:53 UTC, esh4 commented on src/main/java/frc/robot/RobotConstants.java
> +        /**
Factor or franction

2019-01-27 18:53 UTC, esh4 commented on src/main/java/frc/robot/Subsystems/Lift.java
> +  }
Returns a double

2019-01-27 19:48 UTC, esh4 requested changes

2019-01-27 19:48 UTC, esh4 commented on src/main/java/frc/robot/Subsystems/Lift.java
> +    return this.potentiometer.get();
double

2019-01-28 15:46 UTC, esh4 approved these changes

2019-01-28 15:48 UTC, merged