Hatch holder
Programming-Trigon/2019RobotCode pull request #3
Opened 2019-01-23 18:59 UTC by Mboesn

2019-01-24 16:22 UTC, HilelAmiel requested changes
DoubleSolenoid not Solenoid

2019-01-24 16:22 UTC, HilelAmiel commented on src/main/java/frc/robot/RobotMap.java
> +}
names: HATCH_HOLDER_CATCH_SOLENOID, HATCH_HOLDER_RIGHT_PUSH_SOLENOID, HATCH_HOLDER_LEFT_PUSH_SOLENOID

2019-01-24 16:22 UTC, HilelAmiel commented on src/main/java/frc/robot/SubSystem/HatchHolder.java
> +  public HatchHolder(Solenoid frontSolenoid, Solenoid rightBackSolenoid, Solenoid leftBackSolenoid){
change class to DoubleSolenoid (not Solenoid) and all the functions in this class acording to this calss...
names: catchSolenoid, rightPushSolenoid, leftPushSolenoid

2019-01-27 19:49 UTC, esh4 requested changes

2019-01-27 19:49 UTC, esh4 commented on src/main/java/frc/robot/SubSystems/HatchHolder.java
> +    this.pvcSolenoid.set(value);
DoubleSolenoid.Value

2019-01-27 19:49 UTC, esh4 commented on src/main/java/frc/robot/SubSystems/HatchHolder.java
> +    this.leftPushSolenoid.set(value);
DoubleSolenoid.Value

2019-01-28 15:44 UTC, esh4 commented on src/main/java/frc/robot/SubSystems/HatchHolder.java
> +    this.pvcSolenoid.set(value);
cool

2019-01-28 15:44 UTC, esh4 approved these changes

2019-01-28 15:46 UTC, merged